"""rename quiz name column to title

Revision ID: 1f1478f2f397
Revises: a178bb4af31c
Create Date: 2024-10-13 17:10:06.605399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1478f2f397'
down_revision: Union[str, None] = 'a178bb4af31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('title', sa.String(length=150), nullable=False))
    op.drop_constraint('quizes_name_key', 'quizes', type_='unique')
    op.create_unique_constraint(None, 'quizes', ['title'])
    op.drop_column('quizes', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quizes', type_='unique')
    op.create_unique_constraint('quizes_name_key', 'quizes', ['name'])
    op.drop_column('quizes', 'title')
    # ### end Alembic commands ###
