"""delete is_teacher column

Revision ID: 379317f5ed7d
Revises: efcee372bfa5
Create Date: 2024-08-22 18:29:59.916112

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '379317f5ed7d'
down_revision: Union[str, None] = 'efcee372bfa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_teacher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_teacher', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
