"""add answer option sequence number column

Revision ID: 592ce200f2e0
Revises: 148c792d2c41
Create Date: 2024-10-14 17:26:39.643542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592ce200f2e0'
down_revision: Union[str, None] = '148c792d2c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_options', sa.Column('sequence_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_options', 'sequence_number')
    # ### end Alembic commands ###
