"""delete question_type table

Revision ID: 8130bf49d298
Revises: efee264c1bb6
Create Date: 2024-10-13 18:32:14.484502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8130bf49d298'
down_revision: Union[str, None] = 'efee264c1bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_question_type_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'question_type_id')
    op.add_column('user_answers', sa.Column('answer_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user_answers', 'answer_options', ['answer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_answers', 'answer')
    op.drop_table('question_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_column('user_answers', 'answer_id')
    op.add_column('questions', sa.Column('question_type_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('questions_question_type_id_fkey', 'questions', 'question_types', ['question_type_id'], ['id'], ondelete='CASCADE')
    op.create_table('question_types',
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='question_types_pkey'),
    sa.UniqueConstraint('name', name='question_types_name_key')
    )
    # ### end Alembic commands ###
