"""create default user_answers.is_correct=False

Revision ID: e67f6e1173f5
Revises: 592ce200f2e0
Create Date: 2024-10-22 15:53:40.748762

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e67f6e1173f5'
down_revision: Union[str, None] = '592ce200f2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
