services:
  postgres:
    image: 'postgres:16.2'
    env_file: .env
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 1s
      timeout: 1s
      retries: 60
    restart: always
  clickhouse:
    image: 'clickhouse/clickhouse-server:24'
    env_file: .env
    ports:
      - "8123:8123"
  grafana:
    image: 'grafana/grafana-oss:11.3.0'
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  backend:
    build: .
    env_file: .env
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    stop_signal: SIGINT
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  grafana-storage: