services:
  postgres:
    image: 'postgres:16.2'
    env_file: .env
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 1s
      timeout: 1s
      retries: 60
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    restart: always
  clickhouse:
    image: 'clickhouse/clickhouse-server:24'
    env_file: .env
    ports:
      - "8123:8123"
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:${CLICKHOUSE_PORT}/ping || exit 1
      interval: 1s
      timeout: 1s
      retries: 60
    volumes:
      - clickhouse-storage:/var/lib/clickhouse
    restart: always
  prometheus:
    image: 'prom/prometheus:v2.55.1'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
  grafana:
    image: 'grafana/grafana-oss:11.3.0'
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always
  backend:
    build: .
    env_file: .env
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    stop_signal: SIGINT
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    restart: always

volumes:
  postgres-storage:
  clickhouse-storage:
  grafana-storage: